MeeSoftetchWebsite/Controllers/CareersAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MeeSoftetchWebsite.Models;
using Microsoft.AspNet.Identity;
namespace MeeSoftetchWebsite.Controllers
{
     [Authorize]
    public class CareersAdminController : Controller
    {
        private CareersDbContext db = new CareersDbContext();

        
         // GET: /CareersAdmin/
         [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.CareersDb.ToList());
        }

        // GET: /CareersAdmin/Details/5
         [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Careers careers = db.CareersDb.Find(id);
            if (careers == null)
            {
                return HttpNotFound();
            }
            return View(careers);
        }

        // GET: /CareersAdmin/Create
         [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            var careers = new Careers();

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Careers careers)
        {
            if (ModelState.IsValid)
            {
                var newCareerTemp = new Careers
                {
                    OpeningTitle = careers.OpeningTitle,
                    IsOpen = careers.IsOpen,
                    Description = careers.Description,
                    ExperienceMonth = careers.ExperienceMonth,
                    ExperienceYear = careers.ExperienceYear,
                    //TODO: Change it to idendentity user
                    PostedByEmployee = (string)Session["ApplicationEmployeeName"],
                    JobPostingDate = DateTime.Now,
                    SkillsRequired = careers.SkillsRequired
                };
                db.CareersDb.Add(newCareerTemp);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(careers);
        }

        // GET: /CareersAdmin/Edit/5
         [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Careers careers = db.CareersDb.Find(id);
            if (careers == null)
            {
                return HttpNotFound();
            }
            return View(careers);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Careers careers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(careers).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(careers);
        }

        // GET: /CareersAdmin/Delete/5
         [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Careers careers = db.CareersDb.Find(id);
            if (careers == null)
            {
                return HttpNotFound();
            }
            return View(careers);
        }

        // POST: /CareersAdmin/Delete/5
         [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Careers careers = db.CareersDb.Find(id);
            db.CareersDb.Remove(careers);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Applicants()
        {
            var dbInstance = new MeeSoftetchWebsite.Models.CareersRegistration.CareersRegistrationDbContext();
            
            var selectApplicantGroup = dbInstance.careersDb.GroupBy(m => m.AppliedFor);


            ViewBag.ApplicantList = selectApplicantGroup;
            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AjaxRequestApplicants()
        {
            var dbInstance = new MeeSoftetchWebsite.Models.CareersRegistration.CareersRegistrationDbContext();

            var selectApplicantGroup = from n in dbInstance.careersDb
                                           select n;
            ViewBag.FilteredSearch = selectApplicantGroup;
               return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult AjaxRequestApplicants(string searchString)
        {
            var dbInstance = new MeeSoftetchWebsite.Models.CareersRegistration.CareersRegistrationDbContext();

            var selectApplicants = from n in dbInstance.careersDb
                                   select n;

            var filterApplicants = from n in selectApplicants
                                   where n.KeySkills.Contains(searchString) ||
                                   n.ResumePlainText.Contains(searchString) || n.Name.Contains(searchString)
                                   select n;

            ViewBag.FilteredSearch = filterApplicants;
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MeeSoftetchWebsite/Views/CareersAdmin/AjaxRequestApplicants.cshtml
@using MeeSoftetchWebsite.Models;
@{
    ViewBag.Title = "AjaxRequestApplicants";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Search Applicants</h2>
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("AjaxRequestApplicants", "CareersAdmin", FormMethod.Post))
        {
            <div class="form-group">
                <h4>Search</h4><h6>Search by Name/Key Skills/Skills on resume</h6>
                <div class="col-md-10">
                    @Html.TextBox("searchString", "", new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <input type="submit" class="btn-success" value="Search" />
            </div>
        }
        <div class="table-responsive">
            <table id="myDataTable" class="table">
                <tr>
                    <td>Name</td>
                    <td>Exp(Y)</td>
                    <td>Exp(M)</td>
                    <td>Skills</td>
                    <td>Qualification</td>
                    <td>Resume</td>
                    <td>Contact No.</td>
                    <td>Email</td>
                </tr>
                @foreach (var item in ViewBag.FilteredSearch)
                {
                    <tr>
                            <td>@item.Name</td>
                            <td>@item.ExperienceYear</td>
                            <td>@item.ExperienceMonth</td>
                            <td>@item.KeySkills</td>
                            <td>@item.SelectedHighestQualification</td>
                            <td>@item.ResumePlainText</td>
                            <td>@item.ContactNumber</td>
                            <td>@item.EmailAddress</td>
                        </tr>
                }
            </table>
        </div>
    </div>
</div>

MeeSoftetchWebsite/Views/CareersAdmin/Applicants.cshtml
@model MeeSoftetchWebsite.Models.CareersRegistration

@{
    ViewBag.Title = "Applicants";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <td>Name</td>
                    <td>Exp(Y)</td>
                    <td>Exp(M)</td>
                    <td>Skills</td>
                    <td>Qualification</td>
                    <td>Resume</td>
                    <td>Contact No.</td>
                    <td>Email</td>
                </tr>
                @foreach (var applicant in ViewBag.ApplicantList)
                {
                    var i=0;
                    foreach (var item in applicant)
                    {
                        if(i==0)
                        {
                            <tr><td>Opening:@item.AppliedFor</td> </tr>
                        }
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.ExperienceYear</td>
                            <td>@item.ExperienceMonth</td>
                            <td>@item.KeySkills</td>
                            <td>@item.SelectedHighestQualification</td>
                            <td>@item.ResumePlainText</td>
                            <td>@item.ContactNumber</td>
                            <td>@item.EmailAddress</td>
                        </tr>
                        i++;
                    }
                }
            </table>
        </div>
    </div> 
</div>

MeeSoftetchWebsite/Views/CareersAdmin/Create.cshtml
@model MeeSoftetchWebsite.Models.Careers

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create a New Opening</h2>
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Careers</h4>
                <hr />
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.OpeningTitle, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.OpeningTitle, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.OpeningTitle)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ExperienceYear, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.ExperienceYear, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ExperienceYear)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ExperienceMonth, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.ExperienceMonth, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ExperienceMonth)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SkillsRequired, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.SkillsRequired, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.SkillsRequired)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })

                        @*@Html.(model => model.Description, new { @class = "form-control" })*@
                       @* @Html.(model => model.Description, new { @class = "form-control" })*@
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsOpen, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @*@Html.DropDownListFor(model => model.IsOpen, (IEnumerable<SelectListItem>)ViewBag.IsOpenList, new { @class = "form-control" })*@
                        @Html.TextBoxFor(model => model.IsOpen, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IsOpen)
                    </div>
                </div>

                @*<div class="form-group">
                    @Html.LabelFor(model => model.JobPostingDate, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.JobPostingDate)
                        @Html.ValidationMessageFor(model => model.JobPostingDate)
                    </div>
                </div>*@

                @*<div class="form-group">
                    @Html.LabelFor(model => model.PostedByEmployee, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PostedByEmployee)
                        @Html.ValidationMessageFor(model => model.PostedByEmployee)
                    </div>
                </div>*@

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

MeeSoftetchWebsite/Views/CareersAdmin/Delete.cshtml
@model MeeSoftetchWebsite.Models.Careers

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>
<div class="row">
    <div class="col-md-12">
        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Careers</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.OpeningTitle)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.OpeningTitle)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ExperienceYear)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ExperienceYear)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ExperienceMonth)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ExperienceMonth)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.SkillsRequired)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SkillsRequired)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IsOpen)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IsOpen)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.JobPostingDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.JobPostingDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PostedByEmployee)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PostedByEmployee)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
    </div>
</div>

MeeSoftetchWebsite/Views/CareersAdmin/Details.cshtml
@model MeeSoftetchWebsite.Models.Careers

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>
<div class="row">
    <div class="col-md-12">
        <div>
            <h4>Careers</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.OpeningTitle)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.OpeningTitle)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ExperienceYear)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ExperienceYear)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ExperienceMonth)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ExperienceMonth)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.SkillsRequired)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SkillsRequired)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IsOpen)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IsOpen)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.JobPostingDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.JobPostingDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PostedByEmployee)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PostedByEmployee)
                </dd>

            </dl>
        </div>
        
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

MeeSoftetchWebsite/Views/CareersAdmin/Edit.cshtml
@model MeeSoftetchWebsite.Models.Careers

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Careers</h4>
                <hr />
                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.OpeningTitle, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.OpeningTitle)
                        @Html.ValidationMessageFor(model => model.OpeningTitle)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ExperienceYear, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ExperienceYear)
                        @Html.ValidationMessageFor(model => model.ExperienceYear)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ExperienceMonth, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ExperienceMonth)
                        @Html.ValidationMessageFor(model => model.ExperienceMonth)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SkillsRequired, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SkillsRequired)
                        @Html.ValidationMessageFor(model => model.SkillsRequired)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description)
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsOpen, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.IsOpen)
                        @Html.ValidationMessageFor(model => model.IsOpen)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.JobPostingDate, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.JobPostingDate)
                        @Html.ValidationMessageFor(model => model.JobPostingDate)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PostedByEmployee, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PostedByEmployee)
                        @Html.ValidationMessageFor(model => model.PostedByEmployee)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

MeeSoftetchWebsite/Views/CareersAdmin/Index.cshtml
@model IEnumerable<MeeSoftetchWebsite.Models.Careers>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="row">
    <div class="table-responsive">
        <table class="table">
            <tr>
                <th>
                    @*@Html.DisplayNameFor(model => model.OpeningTitle)*@
                    Job Title
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.ExperienceYear)*@
                    Exp.(Year)
                </th>
                <th>
                    Exp.(Month)
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.SkillsRequired)*@
                    Skills Required
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.Description)*@
                    Description
                </th>
                <th>
                   @*Html.DisplayNameFor(model => model.IsOpen)*@
                    Open
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.JobPostingDate)*@
                    Posting Date
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.PostedByEmployee)*@
                    Posted by
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.OpeningTitle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExperienceYear)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExperienceMonth)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SkillsRequired)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsOpen)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.JobPostingDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PostedByEmployee)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>